import { useState } from "react";
import { Redirect } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import BrandLogo from "@/src/components/BrandLogo";
import { PrimaryButton } from "@/src/components/ui";
import { colors } from "@/src/theme";
import { useAuth } from "@/src/store/auth";
export default function LoginScreen(){
 const {session,loading,signIn,signUp}=useAuth(); const[mode,setMode]=useState<"login"|"signup">("login"); const[firstName,setFirstName]=useState(""); const[email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[message,setMessage]=useState<string|null>(null); const[busy,setBusy]=useState(false);
 if(loading)return <View style={styles.center}><ActivityIndicator/></View>; if(session)return <Redirect href="/(tabs)"/>;
 async function submit(){setBusy(true);setMessage(null);const error=mode==="login"?await signIn(email.trim(),password):await signUp(email.trim(),password,firstName.trim());setBusy(false);if(error)setMessage(error);else if(mode==="signup"){setMessage("Compte créé. Vérifie ton email si la confirmation est activée.");setMode("login")}}
 return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><BrandLogo/><View style={styles.heading}><Text style={styles.kicker}>{mode==="login"?"ESPACE MEMBRE":"REJOINDRE EVOLVE"}</Text><Text style={styles.title}>{mode==="login"?"Connexion":"Créer un compte"}</Text><Text style={styles.subtitle}>{mode==="login"?"Retrouve ton programme, tes performances et ton suivi.":"Crée ton accès en quelques secondes."}</Text></View><View style={styles.form}>{mode==="signup"&&<><TextInput value={firstName} onChangeText={setFirstName} placeholder="Prénom" placeholderTextColor={colors.muted2} style={styles.input}/></>}<TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Adresse email" placeholderTextColor={colors.muted2} style={styles.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Mot de passe" placeholderTextColor={colors.muted2} style={styles.input}/>{message?<Text style={styles.message}>{message}</Text>:null}{busy?<ActivityIndicator/>:<PrimaryButton label={mode==="login"?"SE CONNECTER":"CRÉER LE COMPTE"} onPress={submit}/>}</View><Pressable onPress={()=>{setMode(mode==="login"?"signup":"login");setMessage(null)}}><Text style={styles.switch}>{mode==="login"?"Pas encore de compte ? Créer un compte":"Déjà membre ? Se connecter"}</Text></Pressable></ScrollView>
}
const styles=StyleSheet.create({page:{flexGrow:1,paddingHorizontal:24,paddingTop:24,paddingBottom:38,backgroundColor:colors.bg,justifyContent:"center"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:colors.bg},heading:{marginTop:4,marginBottom:24},kicker:{color:colors.yellow,fontSize:10,fontWeight:"900",letterSpacing:2.4,marginBottom:8},title:{color:colors.text,fontSize:38,fontWeight:"800",letterSpacing:-1.2},subtitle:{color:colors.muted,fontSize:14,lineHeight:21,marginTop:7,maxWidth:320},form:{gap:14},input:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,color:colors.text,borderRadius:16,paddingHorizontal:16,paddingVertical:15,fontSize:16},message:{color:colors.muted,lineHeight:20,fontSize:13},switch:{color:colors.yellow,textAlign:"center",fontWeight:"800",paddingVertical:20},roleRow:{flexDirection:"row",gap:10},roleButton:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingVertical:13,alignItems:"center",backgroundColor:colors.surface},roleActive:{backgroundColor:colors.yellow,borderColor:colors.yellow},roleText:{color:colors.text,fontWeight:"900",fontSize:13},roleTextActive:{color:"#0B0B0B"}});
