import React from "react";
import { Pressable, StyleSheet, Text, View, ViewStyle } from "react-native";
import { colors, radius } from "@/src/theme";
export function ScreenHeader({eyebrow="EVOLVE TRAINING",title,subtitle}:{eyebrow?:string;title:string;subtitle?:string}){return <View style={styles.header}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text>{subtitle?<Text style={styles.muted}>{subtitle}</Text>:null}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[styles.card,style]}>{children}</View>}
export function Label({children}:{children:React.ReactNode}){return <Text style={styles.label}>{children}</Text>}
export function Metric({value,label,accent=colors.text}:{value:string;label:string;accent?:string}){return <View style={{gap:4}}><Text style={[styles.metric,{color:accent}]}>{value}</Text><Text style={styles.muted}>{label}</Text></View>}
export function PrimaryButton({label,onPress,disabled}:{label:string;onPress?:()=>void;disabled?:boolean}){return <Pressable onPress={onPress} disabled={disabled} style={({pressed})=>[styles.button,disabled&&{opacity:.4},pressed&&!disabled&&{opacity:.85}]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({header:{gap:6,marginBottom:24},eyebrow:{color:colors.yellow,fontWeight:"800",letterSpacing:2.2,fontSize:11},title:{color:colors.text,fontSize:31,lineHeight:36,fontWeight:"800",letterSpacing:-.9},muted:{color:colors.muted,fontSize:14,lineHeight:21},card:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.lg,padding:18},label:{color:colors.muted,textTransform:"uppercase",fontWeight:"800",fontSize:10,letterSpacing:1.2},metric:{fontSize:23,fontWeight:"800",letterSpacing:-.4},button:{minHeight:56,borderRadius:radius.md,backgroundColor:colors.yellow,alignItems:"center",justifyContent:"center",paddingHorizontal:20},buttonText:{color:"#0B0B0B",fontSize:14,fontWeight:"900",letterSpacing:.7}});
